### ISSUE TITLE
panic on goja.New()

### ISSUE THREAD

**Issue by technosophos** [dop251/goja#36]
The following code produces a panic:

```go
package main

import (
	"github.com/dop251/goja"
)

func main() {
	goja.New()
}
```

Output:

```
⇒  go run main.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x11659fb]

goroutine 1 [running]:
github.com/deis/dhow/vendor/golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
	/Users/technosophos/Code/Go/src/github.com/deis/dhow/vendor/golang.org/x/text/collate/option.go:30 +0x6b
github.com/deis/dhow/vendor/golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42003ff78)
	/Users/technosophos/Code/Go/src/github.com/deis/dhow/vendor/golang.org/x/text/collate/collate.go:60 +0xbc
github.com/deis/dhow/vendor/github.com/dop251/goja.init()
	/Users/technosophos/Code/Go/src/github.com/deis/dhow/vendor/github.com/dop251/goja/builtin_string.go:15 +0x133
main.init()
	/Users/technosophos/Code/Go/src/github.com/deis/dhow/cmd/main.go:10 +0x44
exit status 2
```

Go version:

```
⇒  go version
go version go1.8.3 darwin/amd64
```

Complete dependencies:

```
⇒  cat glide.lock
hash: f21c0c8c2f06ddf1910034af4875b3baa5e8a8338b33eb8da97e8e5779af078a
updated: 2017-07-01T15:23:06.031128545-06:00
imports:
- name: github.com/dlclark/regexp2
  version: 902a5ce7a7812e2ba9f73b9d96c09d5136df39cd
  subpackages:
  - syntax
- name: github.com/dop251/goja
  version: 8f3380f012a7a699e478fcff1d0e46a6f2e1abc5
  subpackages:
  - ast
  - file
  - parser
  - token
- name: golang.org/x/text
  version: 2910a502d2bf9e43193af9d68ca516529614eed3
  subpackages:
  - cases
  - collate
  - collate/colltab
  - internal/colltab
  - internal/tag
  - language
  - transform
  - unicode/norm
testImports: []
```
